version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: chandrudb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql_new_data:/var/lib/mysql
    networks:
      - twotier
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


  flask-app:
    image: chandrukr36/flask-app:latest
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql1
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: chandrudb
    networks:
      - twotier
    depends_on:
      mysql:
        condition: service_healthy

networks:
  twotier:

volumes:
  mysql_new_data:
